// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// THE BODY AS DRAWN — the figure the HUD's body panel paints (`hud-body.tsx`),
// as geometry and nothing else. DOM-free, so the root suite holds it and
// `make damage` draws it.
//
// THE FIGURE IS MADE FROM A WHOLE BODY (`body-model.ts`, GENERATED by `make
// hud-body` off one man's CT, every bone and the skin a mesh of its own):
// the classic anatomical figure standing with the palms forward, the feet
// turned down about the ankles so the toes show side by side, seen two ways
// —
//   - FROM THE FRONT (`FRONT_VIEW`, what the HUD shows): his right on the
//     viewer's left, the trunk's bones cut along the spine and only what lies
//     before the cut drawn (the ribs' front arcs, the sternum, the vertebral
//     bodies, the front of the pelvis); the back, which the front hides, a
//     strip behind the spine (`strip`);
//   - FROM BEHIND (`BACK_VIEW`, there for whoever wants it): his right on the
//     viewer's right, what lies behind the cut (the shoulder blades, the
//     ribs' backs, the vertebral arches, the sacrum), the trunk the back.
// The skull and the limbs are whole in both. In each the skin's silhouette is
// the outline, the twenty parts (`BODY_PARTS`) are cut out of it at the
// body's own seams (the jaw, the sternal notch, the armpits, the costal
// margin, the iliac crests, the groin, the knees, the ankles, the wrists),
// every bone is its silhouette with its holes and its shading, the bones go
// down in the order their depths say, and each has a MARK — the point a
// crack or a break is drawn across, and the bone's way there.

import type { Bone } from "@engine";

import { FIGURE } from "./body-frame.ts";
import { BACK_VIEW, FRONT_VIEW, type BoneDraw, type FigureView } from "./body-model.ts";

export { BACK_VIEW, FIGURE, FRONT_VIEW, type BoneDraw, type FigureView };

/** Which way the figure is seen. */
export type FigureSide = "front" | "back";

/** The figure seen one way. */
export function figureView(side: FigureSide): FigureView {
  return side === "back" ? BACK_VIEW : FRONT_VIEW;
}

type Pt = readonly [number, number];

const f = (n: number): string => (Math.round(n * 10) / 10).toString();

/** A closed polygon as a path. */
function poly(points: readonly Pt[]): string {
  return `M${points.map((p) => `${f(p[0])},${f(p[1])}`).join("L")}Z`;
}

/** THE LONG BONES, which a break parts end to end; the rest (a group of
 * small bones, a flat one) part only near the break. */
const LONG = /^(humerus|radius|ulna|femur|tibia|fibula|clavicle)/;

/** HOW A BONE FRACTURES — the bone's own geometry cut, never a mark drawn
 * on it; deterministic per bone. Every fracture runs along one irregular
 * line across the bone at its mark, skewed as a real fracture line runs:
 *   - a HAIRLINE is an incomplete crack: a fissure (`fissure`) cut into the
 *     bone from one edge along that line, tapering shut short of the far
 *     edge — the flesh shows through it;
 *   - a BREAK is complete: the bone cut along the line, its far side
 *     (`piece`, a long bone's whole far end, a flat or small bone's only
 *     near the line) displaced and angulated (`move`), with the bone less
 *     that piece (`rest`, filled even-odd) left where it was; and a long
 *     bone's break knocks out a butterfly fragment (`chip`) that is set
 *     apart on its own (`chipMove`). */
export type FractureDraw = {
  fissure: string;
  piece: string;
  rest: string;
  move: string;
  chip: string;
  chipMove: string;
};

/** A small, fixed sequence of numbers in [0, 1) off a bone's name. */
function jitter(bone: Bone): () => number {
  let h = 2166136261;
  for (let i = 0; i < bone.length; i++) h = Math.imul(h ^ bone.charCodeAt(i), 16777619);
  return () => {
    h = Math.imul(h ^ (h >>> 15), 2246822507);
    h = Math.imul(h ^ (h >>> 13), 3266489909);
    h ^= h >>> 16;
    return (h >>> 0) / 4294967296;
  };
}

/** The plane outside everything, for a complement filled even-odd. */
export const EVERYWHERE = `M-20,-20H${FIGURE.w + 20}V${FIGURE.h + 20}H-20Z`;

export function fractureOf(bone: Bone, side: FigureSide = "front"): FractureDraw {
  const m = figureView(side).bones[bone].mark;
  const rnd = jitter(bone);
  const long = LONG.test(bone);
  // Across the bone, and along it.
  const skew = (rnd() - 0.5) * 0.8;
  const u: Pt = [Math.cos(m.a + Math.PI / 2 + skew), Math.sin(m.a + Math.PI / 2 + skew)];
  const v: Pt = [Math.cos(m.a), Math.sin(m.a)];
  const at = (t: number, z: number): Pt => [m.x + u[0] * t + v[0] * z, m.y + u[1] * t + v[1] * z];
  // The fracture line: from well past one edge to well past the other.
  const half = m.r * 1.6 + 0.8;
  const N = 10;
  const zig = Math.min(0.5, 0.12 + m.r * 0.16);
  const ts: number[] = [];
  const zs: number[] = [];
  for (let i = 0; i <= N; i++) {
    ts.push(-half + (2 * half * i) / N);
    zs.push((rnd() - 0.5) * 2 * zig);
  }
  const pts = ts.map((t, i) => at(t, zs[i]));
  // THE FISSURE: from the near edge (well outside it) along the line to a
  // little past the mark, as wide as a hair at its mouth and shut at its
  // end.
  const k = Math.round(N * 0.72);
  const mouth = Math.min(0.62, 0.3 + m.r * 0.1);
  const wid = (i: number): number => (mouth * (k - i)) / k;
  const fissure = poly([
    ...pts.slice(0, k + 1).map((_, i) => at(ts[i], zs[i] + wid(i) / 2)),
    ...pts
      .slice(0, k + 1)
      .map((_, i) => at(ts[i], zs[i] - wid(i) / 2))
      .reverse(),
  ]);
  // THE BREAK: everything past the line, as far as the piece reaches.
  const reach = long ? 60 : Math.max(2.4, m.r * 2.6);
  const far = (p: Pt): Pt => [p[0] + v[0] * reach, p[1] + v[1] * reach];
  const wide = long ? half + 40 : half;
  const piece = poly([
    at(-wide, zs[0]),
    ...pts,
    at(wide, zs[N]),
    far(at(wide, zs[N])),
    far(at(-wide, zs[0])),
  ]);
  const sign = rnd() < 0.5 ? -1 : 1;
  // Displaced as a broken bone is: shifted across by about half its width,
  // the ends drawn a little apart, and angulated.
  const slide = 0.4 + m.r * 0.2;
  const sideways = (0.3 + m.r * 0.55) * sign;
  const turn = sign * (6 + rnd() * 6);
  const move = `translate(${f(v[0] * slide + u[0] * sideways)} ${f(v[1] * slide + u[1] * sideways)}) rotate(${f(turn)} ${f(m.x)} ${f(m.y)})`;
  // THE BUTTERFLY: a wedge of the far side, its base on the line about the
  // mark, knocked out the other way.
  const c = N >> 1;
  const apex = at(ts[c] + (rnd() - 0.5) * m.r * 0.4, zs[c] + m.r * 0.95 + 0.3);
  const chip = long ? poly([pts[c - 2], pts[c - 1], pts[c], pts[c + 1], apex]) : "";
  const kick = -sign * (0.4 + m.r * 0.3);
  const chipMove = `translate(${f(u[0] * kick + v[0] * slide * 0.4)} ${f(u[1] * kick + v[1] * slide * 0.4)}) rotate(${f(-turn * 2)} ${f(apex[0])} ${f(apex[1])})`;
  return {
    fissure,
    piece: chip ? `${piece}${chip}` : piece,
    rest: `${EVERYWHERE}${piece}`,
    move,
    chip,
    chipMove,
  };
}
