// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// THE BODY AS DRAWN — the figure the HUD's body panel paints (`hud-body.tsx`),
// as geometry and nothing else. DOM-free, so the root suite holds it and
// `make damage` draws it.
//
// THE FIGURE IS MADE FROM A WHOLE BODY (`body-model.ts`, GENERATED by `make
// hud-body` off one man's CT, every bone and the skin a mesh of its own):
// the classic anatomical figure standing with the palms forward, the feet
// turned down about the ankles so the toes show side by side, seen two ways
// —
//   - FROM THE FRONT (`FRONT_VIEW`, what the HUD shows): his right on the
//     viewer's left, the trunk's bones cut along the spine and only what lies
//     before the cut drawn (the ribs' front arcs, the sternum, the vertebral
//     bodies, the front of the pelvis); the back, which the front hides, a
//     strip behind the spine (`strip`);
//   - FROM BEHIND (`BACK_VIEW`, there for whoever wants it): his right on the
//     viewer's right, what lies behind the cut (the shoulder blades, the
//     ribs' backs, the vertebral arches, the sacrum), the trunk the back.
// The skull and the limbs are whole in both. In each the skin's silhouette is
// the outline, the twenty parts (`BODY_PARTS`) are cut out of it at the
// body's own seams (the jaw, the sternal notch, the armpits, the costal
// margin, the iliac crests, the groin, the knees, the ankles, the wrists),
// every bone is its silhouette with its holes and its shading, the bones go
// down in the order their depths say — the ORGANS among them, inside the
// bones that hold them (the skull's cap lifted off the brain) — and each
// bone has a MARK: the point a crack or a break is drawn across, and the
// bone's way there.

import type { Bone } from "@engine";

import { FORCE_MOST } from "./body-tile.ts";
import { FIGURE } from "./body-frame.ts";
import {
  BACK_VIEW,
  FRONT_VIEW,
  type BoneDraw,
  type FigureView,
  type OrganDraw,
} from "./body-model.ts";

export { BACK_VIEW, FIGURE, FRONT_VIEW, type BoneDraw, type FigureView, type OrganDraw };

/** Which way the figure is seen. */
export type FigureSide = "front" | "back";

/** The figure seen one way. */
export function figureView(side: FigureSide): FigureView {
  return side === "back" ? BACK_VIEW : FRONT_VIEW;
}

type Pt = readonly [number, number];

const f = (n: number): string => (Math.round(n * 10) / 10).toString();

/** A closed polygon as a path. */
function poly(points: readonly Pt[]): string {
  return `M${points.map((p) => `${f(p[0])},${f(p[1])}`).join("L")}Z`;
}

/** THE LONG BONES, which break between their joints: both ends stay where
 * the joints hold them and the break is all that moves; the rest (a group
 * of small bones, a flat one) part only near the break. */
const LONG = /^(humerus|radius|ulna|femur|tibia|fibula|clavicle)/;

/** A PIECE'S MOVE off where it lies: turned `deg` about (`ox`, `oy`) and
 * scaled `s` about it, then shifted (`x`, `y`) — figure units. The drawing
 * reads it as a CSS transform (`moveCss`), so a piece can be animated from
 * where it lay to where the break put it; the lab and the suite read it as
 * an SVG one (`moveSvg`). */
export type Move = { x: number; y: number; deg: number; ox: number; oy: number; s: number };

/** A move as an SVG `transform` attribute. */
export function moveSvg(m: Move): string {
  const at = `translate(${f(m.x + m.ox)} ${f(m.y + m.oy)}) rotate(${f(m.deg)})`;
  return m.s === 1
    ? `${at} translate(${f(-m.ox)} ${f(-m.oy)})`
    : `${at} scale(${m.s}) translate(${f(-m.ox)} ${f(-m.oy)})`;
}

/** A move as a CSS transform about its origin (the element's box being the
 * figure's view box, so a CSS pixel is a figure unit). */
export function moveCss(m: Move): { transform: string; origin: string } {
  const scale = m.s === 1 ? "" : ` scale(${m.s})`;
  return {
    transform: `translate(${f(m.x)}px, ${f(m.y)}px) rotate(${f(m.deg)}deg)${scale}`,
    origin: `${f(m.ox)}px ${f(m.oy)}px`,
  };
}

/** HOW A BONE FRACTURES — the bone's own geometry cut, never a mark drawn
 * on it; deterministic per bone, and thrown further apart the harder it was
 * struck (`force`, 0 a break at the least dose that does one … 1 the
 * energy that shatters it … `FORCE_MOST`). Every fracture runs along
 * irregular lines across the bone at its mark, skewed as a real fracture
 * line runs:
 *   - a HAIRLINE is an incomplete crack: a fissure (`fissure`) cut into the
 *     bone from one edge along that line, tapering shut short of the far
 *     edge — deeper and wider the harder it was struck;
 *   - a BREAK is complete: the bone cut along the line into the piece past
 *     it (`piece`) and the rest (`rest`, filled even-odd). A LONG BONE
 *     breaks between its joints: each piece turns about its own joint end
 *     (`restMove`, `move`), so the joints stay where they are and the two
 *     ends at the break are shoved past each other and kinked. A flat or
 *     small bone's piece is only the bone near the line, shifted and turned
 *     about the break;
 *   - a WEDGE is a break that knocks out a butterfly fragment as well
 *     (`chip`, cut out of the piece even-odd), set apart on its own
 *     (`chipMove`) — larger, and thrown further, the harder the blow;
 *   - SHATTERED (`shatter`) is multifragmentary: two lines either side of
 *     the mark, the pieces beyond them moved as a break's are, further, and
 *     the segment between them broken into polygonal fragments (`shards`),
 *     each thrown out from the point of impact and turned. */
export type FractureDraw = {
  fissure: string;
  piece: string;
  rest: string;
  restMove: Move | null;
  move: Move;
  chip: string;
  chipMove: Move;
  shatter: {
    rest: string;
    restMove: Move | null;
    piece: string;
    move: Move;
    shards: { clip: string; move: Move }[];
  };
};

/** A small, fixed sequence of numbers in [0, 1) off a bone's name. */
function jitter(bone: Bone): () => number {
  let h = 2166136261;
  for (let i = 0; i < bone.length; i++) h = Math.imul(h ^ bone.charCodeAt(i), 16777619);
  return () => {
    h = Math.imul(h ^ (h >>> 15), 2246822507);
    h = Math.imul(h ^ (h >>> 13), 3266489909);
    h ^= h >>> 16;
    return (h >>> 0) / 4294967296;
  };
}

/** The plane outside everything, for a complement filled even-odd. */
export const EVERYWHERE = `M-20,-20H${FIGURE.w + 20}V${FIGURE.h + 20}H-20Z`;

/** WHERE A BONE ENDS along `v` from its mark, both ways (the near end
 * negative): the furthest any point of its outline reaches. */
const ENDS = new Map<string, [number, number]>();
function endsOf(bone: Bone, side: FigureSide, v: Pt): [number, number] {
  const key = `${side}:${bone}`;
  let e = ENDS.get(key);
  if (!e) {
    const b = figureView(side).bones[bone];
    const n = (b.fill.match(/-?\d+(?:\.\d+)?/g) ?? []).map(Number);
    let lo = 0;
    let hi = 0;
    for (let i = 0; i + 1 < n.length; i += 2) {
      const z = (n[i] - b.mark.x) * v[0] + (n[i + 1] - b.mark.y) * v[1];
      lo = Math.min(lo, z);
      hi = Math.max(hi, z);
    }
    e = [lo, hi];
    ENDS.set(key, e);
  }
  return e;
}

const DEG = 180 / Math.PI;

/** A LONG BONE'S TWO PIECES turned about their joint ends so that the near
 * piece's end at the break goes `a` and the far piece's `b` across the bone
 * (along `w`, the way a positive turn carries a point ahead of its pivot),
 * the joints unmoved. */
function pinned(
  m: { x: number; y: number },
  v: Pt,
  ends: [number, number],
  a: number,
  b: number,
): [Move, Move] {
  const near = Math.max(1, -ends[0]);
  const far = Math.max(1, ends[1]);
  const A: Pt = [m.x + v[0] * ends[0], m.y + v[1] * ends[0]];
  const B: Pt = [m.x + v[0] * ends[1], m.y + v[1] * ends[1]];
  return [
    { x: 0, y: 0, deg: (a / near) * DEG, ox: A[0], oy: A[1], s: 1 },
    { x: 0, y: 0, deg: (-b / far) * DEG, ox: B[0], oy: B[1], s: 1 },
  ];
}

export function fractureOf(bone: Bone, side: FigureSide = "front", force = 0.5): FractureDraw {
  const m = figureView(side).bones[bone].mark;
  const rnd = jitter(bone);
  const long = LONG.test(bone);
  const hard = Math.min(FORCE_MOST, Math.max(0, force));
  // How far the pieces are thrown: half today's at the least, twice at the
  // most.
  const k = 0.5 + hard;
  // Across the bone, and along it.
  const skew = (rnd() - 0.5) * 0.8;
  const u: Pt = [Math.cos(m.a + Math.PI / 2 + skew), Math.sin(m.a + Math.PI / 2 + skew)];
  const v: Pt = [Math.cos(m.a), Math.sin(m.a)];
  // Square across the bone: the way a turn about a joint carries the break.
  const w: Pt = [-v[1], v[0]];
  const at = (t: number, z: number): Pt => [m.x + u[0] * t + v[0] * z, m.y + u[1] * t + v[1] * z];
  // The fracture line: from well past one edge to well past the other.
  const half = m.r * 1.6 + 0.8;
  const N = 10;
  const zig = Math.min(0.5, 0.12 + m.r * 0.16);
  const ts: number[] = [];
  const zs: number[] = [];
  for (let i = 0; i <= N; i++) {
    ts.push(-half + (2 * half * i) / N);
    zs.push((rnd() - 0.5) * 2 * zig);
  }
  const pts = ts.map((t, i) => at(t, zs[i]));
  // THE FISSURE: from the near edge (well outside it) along the line to
  // past the mark — the further the harder — as wide as a hair at its
  // mouth and shut at its end.
  const deep = Math.min(1, hard / 0.6);
  const kf = Math.round(N * (0.6 + 0.22 * deep));
  const mouth = Math.min(0.62, 0.3 + m.r * 0.1) * (0.75 + 0.5 * deep);
  const wid = (i: number): number => (mouth * (kf - i)) / kf;
  const fissure = poly([
    ...pts.slice(0, kf + 1).map((_, i) => at(ts[i], zs[i] + wid(i) / 2)),
    ...pts
      .slice(0, kf + 1)
      .map((_, i) => at(ts[i], zs[i] - wid(i) / 2))
      .reverse(),
  ]);
  // THE BREAK: everything past the line, as far as the piece reaches — a
  // long bone's to past its far end.
  const reach = long ? 60 : Math.max(2.4, m.r * 2.6);
  const wide = long ? half + 40 : half;
  const piece = poly([
    at(-wide, zs[0]),
    ...pts,
    at(wide, zs[N]),
    at(wide, zs[N] + reach),
    at(-wide, zs[0] + reach),
  ]);
  const sign = rnd() < 0.5 ? -1 : 1;
  // HOW FAR THE ENDS AT THE BREAK ARE SHOVED PAST EACH OTHER (`shove`,
  // about half the bone's width at a middling blow) and both bowed one way
  // (`bow`, the kink).
  const shove = (0.3 + m.r * 0.55) * k;
  const bow = sign * (0.15 + m.r * 0.25) * k;
  const turn = sign * (6 + rnd() * 6) * k;
  const ends = long ? endsOf(bone, side, v) : null;
  let restMove: Move | null = null;
  let move: Move;
  if (ends) {
    [restMove, move] = pinned(m, v, ends, (sign * shove) / 2 + bow, (-sign * shove) / 2 + bow);
  } else {
    // A small bone's piece: shifted across, drawn off, and turned about
    // the break.
    const slide = (0.4 + m.r * 0.2) * k;
    move = {
      x: v[0] * slide + u[0] * shove * sign,
      y: v[1] * slide + u[1] * shove * sign,
      deg: turn,
      ox: m.x,
      oy: m.y,
      s: 1,
    };
  }
  // THE BUTTERFLY: a wedge of the far side, its base on the line about the
  // mark, knocked out across the bone — growing with the blow.
  const c = N >> 1;
  const tall = (m.r * 1.3 + 0.5) * (0.8 + 0.4 * Math.min(1, hard));
  const apex = at(ts[c] + (rnd() - 0.5) * m.r * 0.4, zs[c] + tall);
  const chip = poly([pts[c - 3], pts[c - 2], pts[c - 1], pts[c], pts[c + 1], pts[c + 2], apex]);
  const kick = -sign * (0.6 + m.r * 0.45) * k;
  const chipMove: Move = {
    x: w[0] * kick,
    y: w[1] * kick,
    deg: -turn * 2,
    ox: apex[0],
    oy: apex[1],
    s: 1,
  };
  return {
    fissure,
    piece,
    rest: `${EVERYWHERE}${piece}`,
    restMove,
    move,
    chip,
    chipMove,
    shatter: shatterOf(m, at, v, w, rnd, {
      half,
      wide,
      reach,
      zig,
      long,
      k,
      sign,
      turn,
      shove,
      ends,
    }),
  };
}

/** SHATTERED: a jittered grid of fragments over the segment either side of
 * the mark — two rows along the bone (three struck harder, `k` past 1.7),
 * `COLS` across it, the outer columns reaching past the bone's edges — and
 * the pieces beyond it moved as a break's are. Each fragment is drawn a
 * little smaller than the hole it came out of (`SHRINK`), so the flesh
 * shows between the pieces. */
const COLS = 3;
const SHRINK = 0.86;

function shatterOf(
  m: { x: number; y: number; r: number },
  at: (t: number, z: number) => Pt,
  v: Pt,
  w: Pt,
  rnd: () => number,
  o: {
    half: number;
    wide: number;
    reach: number;
    zig: number;
    long: boolean;
    k: number;
    sign: number;
    turn: number;
    shove: number;
    ends: [number, number] | null;
  },
): FractureDraw["shatter"] {
  // The segment's half-length along the bone: a long bone's splinters run
  // well along the shaft, a flat bone's stay about the blow.
  const L = (o.long ? m.r * 1.3 + 0.9 : m.r * 0.9 + 0.5) * (0.8 + 0.25 * o.k);
  const ROWS = o.k > 1.7 ? 3 : 2;
  // Where the middle column's sides run across the bone, of `half`: a long
  // bone's core is most of its width.
  const core = o.long ? 0.42 : 0.2;
  const grid: Pt[][] = [];
  for (let r = 0; r <= ROWS; r++) {
    const z = -L + (2 * L * r) / ROWS;
    const row: Pt[] = [];
    for (let c = 0; c <= COLS; c++) {
      const edge = c === 0 || c === COLS;
      const t = edge
        ? (c === 0 ? -1 : 1) * o.wide
        : (c === 1 ? -1 : 1) * core * o.half + (rnd() - 0.5) * o.half * 0.2;
      const inner = r > 0 && r < ROWS;
      const jz = (rnd() - 0.5) * 2 * (inner ? L * (0.7 / ROWS) : o.zig * 1.4);
      row.push(at(t, z + jz));
    }
    grid.push(row);
  }
  // The near line and the far one, across the bone's width.
  const far = (p: Pt, by: number): Pt => [p[0] + (at(0, by)[0] - m.x), p[1] + (at(0, by)[1] - m.y)];
  const near = grid[0];
  const last = grid[ROWS];
  const outside = poly([...near, ...near.map((p) => far(p, o.reach + 2 * L)).reverse()]);
  const piece = poly([...last, ...last.map((p) => far(p, o.reach)).reverse()]);
  // The pieces beyond: a long bone's turned about their joints further than
  // a break's, the ends shoved apart; a small bone's far piece thrown off.
  let restMove: Move | null = null;
  let move: Move;
  if (o.ends) {
    const shove = o.shove * 1.4;
    [restMove, move] = pinned(m, v, o.ends, o.sign * shove * 0.6, -o.sign * shove * 0.6);
  } else {
    const fx = at(o.sign * (0.5 + m.r * 0.8) * o.k, o.k * 0.8);
    move = { x: fx[0] - m.x, y: fx[1] - m.y, deg: o.turn * 1.4, ox: m.x, oy: m.y, s: 1 };
  }
  // The fragments, each thrown out from the mark along the way to its
  // middle (read inside the bone's width) and turned about it.
  const shards: { clip: string; move: Move }[] = [];
  for (let r = 0; r < ROWS; r++) {
    for (let c = 0; c < COLS; c++) {
      const cell = [grid[r][c], grid[r][c + 1], grid[r + 1][c + 1], grid[r + 1][c]];
      const side = c - 1;
      const mid = at(
        side * Math.min(m.r * 0.8, (core * o.half + m.r) / 2),
        -L + (2 * L * (r + 0.5)) / ROWS,
      );
      const dx = mid[0] - m.x;
      const dy = mid[1] - m.y;
      const dl = Math.hypot(dx, dy) || 1;
      // Out from the bone first: a long bone's splinters are thrown across
      // it, never along it into a joint.
      const across = dx * w[0] + dy * w[1];
      const ux = o.long ? w[0] * Math.sign(across || 1) : dx / dl;
      const uy = o.long ? w[1] * Math.sign(across || 1) : dy / dl;
      // A long bone's core (the middle column) stays about the shaft, only
      // knocked aside and turned a little; its splinters fly.
      const held = o.long && c === 1 ? 0.3 : 1;
      const throwBy = (0.35 + m.r * 0.45) * o.k * (0.6 + rnd() * 0.8) * held;
      const deg = (rnd() - 0.5) * 50 * o.k * (o.long && c === 1 ? 0.4 : 1);
      shards.push({
        clip: poly(cell),
        move: { x: ux * throwBy, y: uy * throwBy, deg, ox: mid[0], oy: mid[1], s: SHRINK },
      });
    }
  }
  return { rest: `${EVERYWHERE}${outside}`, restMove, piece, move, shards };
}
