// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// THE MODEL REGISTRY: every kind of object the game draws, and whether what
// the player sees is a MODEL made in Blender (`make models`, committed in
// `pwa/models/`, the `blender-assets` skill) or GENERATED by the game's own
// code at run time. One row an asset: its ids, where each half lives and
// the switch that sends a modelled asset back to its code.
//
// A modelled asset keeps its code builder — the switch's other side, and
// what the model is judged against — so every row names one. The ground,
// the sky, the water of a trail, the spray and the snow cloud are surfaces
// and effects, not objects, and are not rows.
//
// `tests/model_registry_test.ts` holds it to the tree: the Blender rows'
// files are exactly the files the build packs (`modelFiles`), every path
// named here exists, and `docs/models.md` carries `renderModelRegistry()`
// (`make model-registry` rewrites it, and prettier pads its columns).
// DOM-free and three-free.

import { CROWD_BODIES, SKI_CATALOG, TREE_KINDS } from "@engine";

import { BEAST_IDS } from "./beast-defs.ts";
import { BIRD_IDS } from "./bird-defs.ts";

export type ModelSource = "blender" | "code";

export type ModelRow = {
  /** What is drawn, in the player's words. */
  asset: string;
  /** Every id of it the game draws. */
  ids: readonly string[];
  /** Where the drawn geometry comes from today. */
  source: ModelSource;
  /** The code that builds it — the only builder of a `code` row, the
   * switched-off one of a `blender` row. */
  code: readonly string[];
  /** What puts it in the scene. */
  drawnBy: string;
  /** A modelled asset's Blender builder, its committed files (published
   * names under `pwa/models/`, and their shape as one pattern), and the
   * build switch that turns it back. */
  blender?: { builder: string; files: readonly string[]; pattern: string; switch: string };
  /** Anything a reader should know that the columns do not say. */
  note?: string;
};

export const MODEL_REGISTRY: readonly ModelRow[] = [
  {
    asset: "Skis",
    ids: SKI_CATALOG.map((s) => s.id),
    source: "blender",
    code: ["pwa/src/game/skis-body.ts", "pwa/src/game/ski-gear.ts"],
    drawnBy: "pwa/src/game/skier-models.ts",
    blender: {
      builder: "scripts/blender/skis.py",
      files: SKI_CATALOG.map((s) => `${s.id}.glb`),
      pattern: "<id>.glb",
      switch: "VITE_MODEL_SKIS",
    },
    note: "the ghost and the ski card draw the same models",
  },
  {
    asset: "Helicopter",
    ids: ["heli"],
    source: "blender",
    code: ["pwa/src/game/heli-view.ts"],
    drawnBy: "pwa/src/game/heli-view.ts",
    blender: {
      builder: "scripts/blender/heli.py",
      files: ["heli.glb"],
      pattern: "heli.glb",
      switch: "VITE_MODEL_HELI",
    },
    note:
      "the free ride's heli-ski machine, built off `HELI`: three rigid nodes (the airframe, " +
      "the main rotor, the tail rotor); the code's stand-in is a cabin, a boom, the skids and the rotors",
  },
  {
    asset: "Snowmobile",
    ids: ["sled"],
    source: "blender",
    code: ["pwa/src/game/sled-view.ts"],
    drawnBy: "pwa/src/game/sled-view.ts",
    blender: {
      builder: "scripts/blender/sled.py",
      files: ["sled.glb"],
      pattern: "sled.glb",
      switch: "VITE_MODEL_SLED",
    },
    note:
      "the free ride's mountain sled, built off `SLED` and the class's trace: rigid nodes (the " +
      "chassis, the bars, each ski, the rear suspension, the paddles with their run morph, the " +
      "ski rack); the code's stand-in is a cowl, a tunnel, a belt and two skis",
  },
  {
    asset: "Piste machine",
    ids: ["groomer"],
    source: "blender",
    code: ["pwa/src/game/groomer-build.ts"],
    drawnBy: "pwa/src/game/groomer-view.ts",
    blender: {
      builder: "scripts/blender/groomer.py",
      files: ["groomer.glb"],
      pattern: "groomer.glb",
      switch: "VITE_MODEL_GROOMER",
    },
    note:
      "the free ride's night groomer at the largest class's true size, built off `GROOMER` and " +
      "the class's layout (`groomer-look.ts`): rigid nodes (the hull, belts, cab and hood; the " +
      "cleats with their run morph; the blade on its hinge; the heap; the tiller on its hitch; " +
      "the beacon's reflector), one model cloned for every machine out; the code's stand-in is " +
      "the same machine in boxes",
  },
  {
    asset: "Skier",
    ids: ["skier"],
    source: "code",
    code: [
      "pwa/src/game/skier-dress.ts",
      "pwa/src/game/dress.ts",
      "pwa/src/game/dress-loft.ts",
      "pwa/src/game/dress-garments.ts",
      "pwa/src/game/dress-head.ts",
      "pwa/src/game/helmet-shape.ts",
    ],
    drawnBy: "pwa/src/game/skier-figure.ts",
    note:
      "procedural: his outfit (outfit.ts — two bodies, five jackets, four pants, four helmets, " +
      "four gloves, four poles) cut to the body's measure on the rig and skinned on it; " +
      "`make blender KIND=skier` still models one suit, the labs' comparison (`make gear`)",
  },
  {
    asset: "Trees",
    ids: [...TREE_KINDS],
    source: "code",
    code: ["pwa/src/game/tree-shapes.ts", "pwa/src/game/tree-mesh.ts"],
    drawnBy: "pwa/src/game/forest.ts",
    note:
      "procedural: ten variants a kind at three levels of detail, the trunk sized " +
      "to the tree's age, painted in the region's colours",
  },
  {
    asset: "Birds",
    ids: BIRD_IDS,
    source: "code",
    code: ["pwa/src/game/bird-shapes.ts", "pwa/src/game/tree-mesh.ts"],
    drawnBy: "pwa/src/game/birds.ts",
    note:
      "procedural: a form for each sex or age that shows — a cock, a hen, a first-winter " +
      "bird — at two levels of detail, each bird its own size and shade, flapped in the shader",
  },
  {
    asset: "Animals",
    ids: BEAST_IDS,
    source: "code",
    code: ["pwa/src/game/beast-shapes.ts", "pwa/src/game/tree-mesh.ts"],
    drawnBy: "pwa/src/game/beasts.ts",
    note:
      "procedural: grown and young forms at two levels of detail, each animal its own " +
      "size and shade, antlers and horns grown to its age in the shader",
  },
  {
    asset: "Amateur skiers",
    ids: CROWD_BODIES,
    source: "code",
    code: [
      "pwa/src/game/crowd-shapes.ts",
      "pwa/src/game/crowd-rig.ts",
      "pwa/src/game/tree-mesh.ts",
    ],
    drawnBy: "pwa/src/game/crowd-view.ts",
    note:
      "procedural: the free ride's crowd — eight bodies at three levels of detail, posed " +
      "by morph targets solved from the player's own pose and dressed per instance",
  },
  {
    asset: "Spectators",
    ids: ["fan-near", "fan-far"],
    source: "code",
    code: ["pwa/src/game/spectator-shapes.ts", "pwa/src/game/spectator-plan.ts"],
    drawnBy: "pwa/src/game/spectators.ts",
    note:
      "procedural: a race's crowd — one rough figure at two levels of detail carrying every " +
      "hat and prop, each fan's look dealt per instance and his moves posed in the shader",
  },
  {
    asset: "The finish arena",
    ids: ["grandstand", "fan-fence", "finish-boards", "exit-gate", "leader-platform", "video-wall"],
    source: "code",
    code: ["pwa/src/game/finish-arena.ts"],
    drawnBy: "pwa/src/game/spectators.ts",
    note: "procedural and boxy, laid out by the crowd's plan; the video wall shows the run clock",
  },
  {
    asset: "Gates, the start hut and the finish arch",
    ids: ["gate-pole", "gate-panel", "edge-pole", "marker", "start-hut", "finish-arch"],
    source: "code",
    code: ["pwa/src/game/mark-shapes.ts", "pwa/src/game/start-arch.ts"],
    drawnBy: "pwa/src/game/gates.ts",
    note: "procedural and faceted; the arch built round the finish line's own plan",
  },
];

const cell = (s: string): string => s.replaceAll("|", "\\|");
const paths = (ps: readonly string[]): string => ps.map((p) => `\`${p}\``).join(", ");

/** The registry as the markdown table `docs/models.md` carries. */
export function renderModelRegistry(rows: readonly ModelRow[] = MODEL_REGISTRY): string {
  const head = [
    "| Asset | Source | Kinds | Blender builder | Committed models | Code builder | Drawn by | Switch |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
  ];
  const body = rows.map((r) => {
    const b = r.blender;
    const models = b ? `${b.files.length} × \`pwa/models/${b.pattern}\`` : "—";
    return `| ${[
      r.asset + (r.note ? ` (${r.note})` : ""),
      r.source === "blender" ? "**Blender**" : "code",
      `${r.ids.length}: ${r.ids.join(", ")}`,
      b ? `\`${b.builder}\`` : "—",
      models,
      paths(r.code),
      `\`${r.drawnBy}\``,
      b ? `\`${b.switch}=0\`` : "—",
    ]
      .map(cell)
      .join(" | ")} |`;
  });
  return [...head, ...body].join("\n");
}

/** The markers the table stands between in `docs/models.md`. */
export const REGISTRY_BEGIN = "<!-- model-registry:begin (make model-registry) -->";
export const REGISTRY_END = "<!-- model-registry:end -->";

/** The table between the markers in `page`. */
export function registryTableIn(page: string): string {
  const a = page.indexOf(REGISTRY_BEGIN);
  const b = page.indexOf(REGISTRY_END);
  if (a < 0 || b < a) throw new Error("docs/models.md has lost its registry markers");
  return page.slice(a + REGISTRY_BEGIN.length, b);
}

/** Two tables that say the same thing, whatever the padding in their cells
 * (prettier aligns the page's columns; the renderer does not). */
export function sameTable(a: string, b: string): boolean {
  const norm = (t: string): string =>
    t
      .split("\n")
      .map((l) =>
        l
          .trim()
          .replace(/\s*\|\s*/g, "|")
          .replace(/-{3,}/g, "---"),
      )
      .filter(Boolean)
      .join("\n");
  return norm(a) === norm(b);
}

/** `page` with the text between the markers replaced by `table`. */
export function withRegistryTable(page: string, table: string): string {
  const a = page.indexOf(REGISTRY_BEGIN);
  const b = page.indexOf(REGISTRY_END);
  if (a < 0 || b < a) throw new Error("docs/models.md has lost its registry markers");
  return `${page.slice(0, a + REGISTRY_BEGIN.length)}\n\n${table}\n\n${page.slice(b)}`;
}
