// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// THE MODEL REGISTRY: every kind of object the game draws, and whether what
// the player sees is a MODEL made in Blender (`make models`, committed in
// `pwa/models/`, the `blender-assets` skill) or GENERATED by the game's own
// code at run time. One row an asset: its ids, where each half lives and
// the switch that sends a modelled asset back to its code.
//
// A modelled asset keeps its code builder — the switch's other side, and
// what the model is judged against — so every row names one. The ground,
// the sky, the water of a trail, the spray and the snow cloud are surfaces
// and effects, not objects, and are not rows.
//
// `tests/model_registry_test.ts` holds it to the tree: the Blender rows'
// files are exactly the files the build packs (`modelFiles`), every path
// named here exists, and `docs/models.md` carries `renderModelRegistry()`
// (`make model-registry` rewrites it, and prettier pads its columns).
// DOM-free and three-free.

import { SKI_CATALOG, TREE_KINDS } from "@engine";

import { BEAST_IDS } from "./beast-defs.ts";
import { BIRD_IDS } from "./bird-defs.ts";
import { GATE_IDS } from "./gate-ids.ts";

export type ModelSource = "blender" | "code";

export type ModelRow = {
  /** What is drawn, in the player's words. */
  asset: string;
  /** Every id of it the game draws. */
  ids: readonly string[];
  /** Where the drawn geometry comes from today. */
  source: ModelSource;
  /** The code that builds it — the only builder of a `code` row, the
   * switched-off one of a `blender` row. */
  code: readonly string[];
  /** What puts it in the scene. */
  drawnBy: string;
  /** A modelled asset's Blender builder, its committed files (published
   * names under `pwa/models/`, and their shape as one pattern), and the
   * build switch that turns it back. */
  blender?: { builder: string; files: readonly string[]; pattern: string; switch: string };
  /** Anything a reader should know that the columns do not say. */
  note?: string;
};

export const MODEL_REGISTRY: readonly ModelRow[] = [
  {
    asset: "Skis",
    ids: SKI_CATALOG.map((s) => s.id),
    source: "blender",
    code: ["pwa/src/game/skis-body.ts", "pwa/src/game/ski-gear.ts"],
    drawnBy: "pwa/src/game/skier-models.ts",
    blender: {
      builder: "scripts/blender/skis.py",
      files: SKI_CATALOG.map((s) => `${s.id}.glb`),
      pattern: "<id>.glb",
      switch: "VITE_MODEL_SKIS",
    },
    note: "the ghost and the ski card draw the same models",
  },
  {
    asset: "Skier",
    ids: ["skier"],
    source: "blender",
    code: [
      "pwa/src/game/skier-figure.ts",
      "pwa/src/game/skier-cloth.ts",
      "pwa/src/game/skier-helmet.ts",
    ],
    drawnBy: "pwa/src/game/skier-models.ts",
    blender: {
      builder: "scripts/blender/skier.py",
      files: ["skier.glb"],
      pattern: "skier.glb",
      switch: "VITE_MODEL_SKIERS",
    },
    note: "one model, dressed in each start-line slot's kit",
  },
  {
    asset: "Trees",
    ids: [...TREE_KINDS],
    source: "code",
    code: ["pwa/src/game/tree-shapes.ts", "pwa/src/game/tree-mesh.ts"],
    drawnBy: "pwa/src/game/forest.ts",
    note:
      "procedural: ten variants a kind at three levels of detail, the trunk sized " +
      "to the tree's age, painted in the region's colours",
  },
  {
    asset: "Birds",
    ids: BIRD_IDS,
    source: "blender",
    code: ["pwa/src/game/bird-shapes.ts"],
    drawnBy: "pwa/src/game/birds.ts",
    blender: {
      builder: "scripts/blender/bird.py",
      files: BIRD_IDS.map((k) => `birds/${k}.glb`),
      pattern: "birds/<id>.glb",
      switch: "VITE_MODEL_BIRDS",
    },
    note: "one model a species, painted in its style, flapped by the same shader",
  },
  {
    asset: "Animals",
    ids: BEAST_IDS,
    source: "blender",
    code: ["pwa/src/game/beast-shapes.ts"],
    drawnBy: "pwa/src/game/beasts.ts",
    blender: {
      builder: "scripts/blender/beast.py",
      files: BEAST_IDS.map((k) => `beasts/${k}.glb`),
      pattern: "beasts/<id>.glb",
      switch: "VITE_MODEL_BEASTS",
    },
    note: "one model a species, painted in its style, walked by the same shader",
  },
  {
    asset: "Gates, the start hut and the finish arch",
    ids: [...GATE_IDS],
    source: "blender",
    code: ["pwa/src/game/gates.ts", "pwa/src/game/start-arch.ts"],
    drawnBy: "pwa/src/game/gates.ts",
    blender: {
      builder: "scripts/blender/gate.py",
      files: GATE_IDS.map((k) => `gates/${k}.glb`),
      pattern: "gates/<id>.glb",
      switch: "VITE_MODEL_GATES",
    },
    note: "the arch stretched to the finish line; the panels, the nets, the edge poles and the floods stay code",
  },
];

const cell = (s: string): string => s.replaceAll("|", "\\|");
const paths = (ps: readonly string[]): string => ps.map((p) => `\`${p}\``).join(", ");

/** The registry as the markdown table `docs/models.md` carries. */
export function renderModelRegistry(rows: readonly ModelRow[] = MODEL_REGISTRY): string {
  const head = [
    "| Asset | Source | Kinds | Blender builder | Committed models | Code builder | Drawn by | Switch |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
  ];
  const body = rows.map((r) => {
    const b = r.blender;
    const models = b ? `${b.files.length} × \`pwa/models/${b.pattern}\`` : "—";
    return `| ${[
      r.asset + (r.note ? ` (${r.note})` : ""),
      r.source === "blender" ? "**Blender**" : "code",
      `${r.ids.length}: ${r.ids.join(", ")}`,
      b ? `\`${b.builder}\`` : "—",
      models,
      paths(r.code),
      `\`${r.drawnBy}\``,
      b ? `\`${b.switch}=0\`` : "—",
    ]
      .map(cell)
      .join(" | ")} |`;
  });
  return [...head, ...body].join("\n");
}

/** The markers the table stands between in `docs/models.md`. */
export const REGISTRY_BEGIN = "<!-- model-registry:begin (make model-registry) -->";
export const REGISTRY_END = "<!-- model-registry:end -->";

/** The table between the markers in `page`. */
export function registryTableIn(page: string): string {
  const a = page.indexOf(REGISTRY_BEGIN);
  const b = page.indexOf(REGISTRY_END);
  if (a < 0 || b < a) throw new Error("docs/models.md has lost its registry markers");
  return page.slice(a + REGISTRY_BEGIN.length, b);
}

/** Two tables that say the same thing, whatever the padding in their cells
 * (prettier aligns the page's columns; the renderer does not). */
export function sameTable(a: string, b: string): boolean {
  const norm = (t: string): string =>
    t
      .split("\n")
      .map((l) =>
        l
          .trim()
          .replace(/\s*\|\s*/g, "|")
          .replace(/-{3,}/g, "---"),
      )
      .filter(Boolean)
      .join("\n");
  return norm(a) === norm(b);
}

/** `page` with the text between the markers replaced by `table`. */
export function withRegistryTable(page: string, table: string): string {
  const a = page.indexOf(REGISTRY_BEGIN);
  const b = page.indexOf(REGISTRY_END);
  if (a < 0 || b < a) throw new Error("docs/models.md has lost its registry markers");
  return `${page.slice(0, a + REGISTRY_BEGIN.length)}\n\n${table}\n\n${page.slice(b)}`;
}
