// SPDX-License-Identifier: ODbL-1.0
// GENERATED by `make real-hints ARGS=--write` (scripts/real-hints.mjs) —
// never edit by hand. Which piste grades each real face's ski area signs,
// read off OpenStreetMap, © OpenStreetMap contributors, under the Open
// Database Licence 1.0 (docs/real-faces.md), and where each face's hints
// are kept (`real-hints/hints-<id>.ts`, loaded only when a map is raised
// on it); `real-hints.ts` reads it.

import type { RunGrade } from "./grades.ts";

/** One face's hints as baked: its id and the bytes, base64. */
export type HintData = {
  readonly id: string;
  readonly data: string;
};

/** A lift's ends and a piste's bends are kept in steps of `coarse` m and
 * the piste's width at each bend in steps of `width` m (0 unknown), a
 * house's middle in steps of `fine` m and its size in steps of `size` m,
 * its bearing in `bearings` steps round half a turn. */
export const HINT_GRAIN = { coarse: 2, fine: 1, size: 1, width: 2, bearings: 32 } as const;

/** The grades of the real pistes on each face that has hints. */
export const HINT_GRADES: Readonly<Record<string, readonly RunGrade[]>> = {
  "alpine-1": ["green", "blue", "red", "black"],
  "alpine-2": ["green", "blue", "red", "black", "orange"],
  "alpine-3": ["green", "blue", "red", "black", "orange"],
  "alpine-4": ["green", "blue", "red", "black", "orange"],
  "alpine-5": ["green", "blue", "red", "black", "orange"],
  "alpine-6": ["green", "blue", "red", "black"],
  "alpine-7": ["blue", "red", "black", "orange"],
  "alpine-8": ["blue", "red", "black", "orange"],
  "alpine-9": ["blue", "red", "black", "orange"],
  "alpine-10": ["red", "black", "orange"],
  "alpine-11": ["blue", "red", "black"],
  "continental-1": ["green", "blue", "black"],
  "continental-2": ["green", "blue", "black", "orange"],
  "continental-3": ["green", "blue", "black", "orange"],
  "continental-4": ["blue", "black"],
  "maritime-1": ["green", "blue", "black", "orange"],
  "maritime-2": ["green", "blue", "black", "orange"],
  "maritime-3": ["green", "blue", "black"],
  "fell-1": ["green", "blue", "red", "black", "orange"],
  "fell-2": ["green", "blue", "red", "black"],
  "fell-3": ["green", "blue", "red", "black", "orange"],
  "fell-4": ["green", "blue", "red", "black"],
  "fell-5": ["green", "blue", "red", "black"],
  "fell-6": ["green", "blue", "red", "black"],
  "fell-7": ["green", "blue", "red", "orange"],
  "fell-8": ["green", "blue", "red", "black"],
  "fell-9": ["green", "blue", "red", "black", "orange"],
  "fell-10": ["green", "blue", "red", "black"],
  "fell-11": ["green", "blue", "red", "black"],
  "fell-12": ["green", "blue", "red", "black"],
  "fell-13": ["green", "blue", "red", "black"],
  "fell-14": ["green", "blue", "red", "black"],
  "fell-15": ["green", "blue", "red", "black"],
  "fell-16": ["green", "blue", "red", "black", "orange"],
  "fell-17": ["green", "blue", "red", "black"],
  "fell-18": ["green", "blue", "red", "black", "orange"],
  "fell-19": ["green", "blue", "red", "black", "orange"],
  "fell-20": ["green", "blue", "red", "black"],
  "fell-21": ["green", "blue", "red", "black"],
  "maritime-4": ["green", "blue", "red", "black"],
};

/** Each face's hints, fetched when a map is raised on it. */
export const HINT_LOADERS: Readonly<Record<string, () => Promise<{ HINTS: HintData }>>> = {
  "alpine-1": () => import("./real-hints/hints-alpine-1.ts"),
  "alpine-2": () => import("./real-hints/hints-alpine-2.ts"),
  "alpine-3": () => import("./real-hints/hints-alpine-3.ts"),
  "alpine-4": () => import("./real-hints/hints-alpine-4.ts"),
  "alpine-5": () => import("./real-hints/hints-alpine-5.ts"),
  "alpine-6": () => import("./real-hints/hints-alpine-6.ts"),
  "alpine-7": () => import("./real-hints/hints-alpine-7.ts"),
  "alpine-8": () => import("./real-hints/hints-alpine-8.ts"),
  "alpine-9": () => import("./real-hints/hints-alpine-9.ts"),
  "alpine-10": () => import("./real-hints/hints-alpine-10.ts"),
  "alpine-11": () => import("./real-hints/hints-alpine-11.ts"),
  "continental-1": () => import("./real-hints/hints-continental-1.ts"),
  "continental-2": () => import("./real-hints/hints-continental-2.ts"),
  "continental-3": () => import("./real-hints/hints-continental-3.ts"),
  "continental-4": () => import("./real-hints/hints-continental-4.ts"),
  "maritime-1": () => import("./real-hints/hints-maritime-1.ts"),
  "maritime-2": () => import("./real-hints/hints-maritime-2.ts"),
  "maritime-3": () => import("./real-hints/hints-maritime-3.ts"),
  "fell-1": () => import("./real-hints/hints-fell-1.ts"),
  "fell-2": () => import("./real-hints/hints-fell-2.ts"),
  "fell-3": () => import("./real-hints/hints-fell-3.ts"),
  "fell-4": () => import("./real-hints/hints-fell-4.ts"),
  "fell-5": () => import("./real-hints/hints-fell-5.ts"),
  "fell-6": () => import("./real-hints/hints-fell-6.ts"),
  "fell-7": () => import("./real-hints/hints-fell-7.ts"),
  "fell-8": () => import("./real-hints/hints-fell-8.ts"),
  "fell-9": () => import("./real-hints/hints-fell-9.ts"),
  "fell-10": () => import("./real-hints/hints-fell-10.ts"),
  "fell-11": () => import("./real-hints/hints-fell-11.ts"),
  "fell-12": () => import("./real-hints/hints-fell-12.ts"),
  "fell-13": () => import("./real-hints/hints-fell-13.ts"),
  "fell-14": () => import("./real-hints/hints-fell-14.ts"),
  "fell-15": () => import("./real-hints/hints-fell-15.ts"),
  "fell-16": () => import("./real-hints/hints-fell-16.ts"),
  "fell-17": () => import("./real-hints/hints-fell-17.ts"),
  "fell-18": () => import("./real-hints/hints-fell-18.ts"),
  "fell-19": () => import("./real-hints/hints-fell-19.ts"),
  "fell-20": () => import("./real-hints/hints-fell-20.ts"),
  "fell-21": () => import("./real-hints/hints-fell-21.ts"),
  "maritime-4": () => import("./real-hints/hints-maritime-4.ts"),
};
