// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// GENERATED by `make real-faces ARGS=--write` (scripts/real-faces.mjs) —
// never edit by hand. Every real face's id, region and country, and where
// its heights are kept (`real-faces/face-<id>.ts`, loaded only when a map
// is raised on it); `real-face.ts` reads it.

import type { RegionId } from "./regions.ts";

/** One face as baked: its region, the lowest height (m) and the grid. */
export type FaceData = {
  readonly id: string;
  readonly region: RegionId;
  readonly floor: number;
  readonly data: string;
};

/** A face as the start card lists it: its region (R21) and the country it
 * lies in (ISO 3166-1 alpha-2). */
export type FaceEntry = {
  readonly id: string;
  readonly region: RegionId;
  readonly country: string;
};

/** The grid's samples a side and their spacing, m, and a height's step, m. */
export const FACE_GRID = { n: 126, cell: 32, step: 0.5 } as const;

export const FACE_INDEX: readonly FaceEntry[] = [
  { id: "alpine-1", region: "alpine", country: "FR" },
  { id: "alpine-2", region: "alpine", country: "FR" },
  { id: "alpine-3", region: "alpine", country: "FR" },
  { id: "alpine-4", region: "alpine", country: "FR" },
  { id: "alpine-5", region: "alpine", country: "FR" },
  { id: "alpine-6", region: "alpine", country: "FR" },
  { id: "alpine-7", region: "alpine", country: "CH" },
  { id: "alpine-8", region: "alpine", country: "CH" },
  { id: "alpine-9", region: "alpine", country: "AT" },
  { id: "alpine-10", region: "alpine", country: "AT" },
  { id: "alpine-11", region: "alpine", country: "AT" },
  { id: "continental-1", region: "continental", country: "US" },
  { id: "continental-2", region: "continental", country: "US" },
  { id: "continental-3", region: "continental", country: "US" },
  { id: "continental-4", region: "continental", country: "US" },
  { id: "maritime-1", region: "maritime", country: "CA" },
  { id: "maritime-2", region: "maritime", country: "JP" },
  { id: "maritime-3", region: "maritime", country: "JP" },
  { id: "fell-1", region: "fell", country: "SE" },
  { id: "fell-2", region: "fell", country: "NO" },
  { id: "fell-3", region: "fell", country: "SE" },
  { id: "fell-4", region: "fell", country: "SE" },
  { id: "fell-5", region: "fell", country: "SE" },
  { id: "fell-6", region: "fell", country: "SE" },
  { id: "fell-7", region: "fell", country: "SE" },
  { id: "fell-8", region: "fell", country: "SE" },
  { id: "fell-9", region: "fell", country: "SE" },
  { id: "fell-10", region: "fell", country: "SE" },
  { id: "fell-11", region: "fell", country: "SE" },
  { id: "fell-12", region: "fell", country: "NO" },
  { id: "fell-13", region: "fell", country: "SE" },
  { id: "fell-14", region: "fell", country: "SE" },
  { id: "fell-15", region: "fell", country: "SE" },
  { id: "fell-16", region: "fell", country: "SE" },
  { id: "fell-17", region: "fell", country: "NO" },
  { id: "fell-18", region: "fell", country: "NO" },
  { id: "fell-19", region: "fell", country: "NO" },
  { id: "fell-20", region: "fell", country: "NO" },
  { id: "fell-21", region: "fell", country: "FI" },
  { id: "maritime-4", region: "maritime", country: "NO" },
];

/** Each face's heights, fetched when a map is raised on it. */
export const FACE_LOADERS: Readonly<Record<string, () => Promise<{ FACE: FaceData }>>> = {
  "alpine-1": () => import("./real-faces/face-alpine-1.ts"),
  "alpine-2": () => import("./real-faces/face-alpine-2.ts"),
  "alpine-3": () => import("./real-faces/face-alpine-3.ts"),
  "alpine-4": () => import("./real-faces/face-alpine-4.ts"),
  "alpine-5": () => import("./real-faces/face-alpine-5.ts"),
  "alpine-6": () => import("./real-faces/face-alpine-6.ts"),
  "alpine-7": () => import("./real-faces/face-alpine-7.ts"),
  "alpine-8": () => import("./real-faces/face-alpine-8.ts"),
  "alpine-9": () => import("./real-faces/face-alpine-9.ts"),
  "alpine-10": () => import("./real-faces/face-alpine-10.ts"),
  "alpine-11": () => import("./real-faces/face-alpine-11.ts"),
  "continental-1": () => import("./real-faces/face-continental-1.ts"),
  "continental-2": () => import("./real-faces/face-continental-2.ts"),
  "continental-3": () => import("./real-faces/face-continental-3.ts"),
  "continental-4": () => import("./real-faces/face-continental-4.ts"),
  "maritime-1": () => import("./real-faces/face-maritime-1.ts"),
  "maritime-2": () => import("./real-faces/face-maritime-2.ts"),
  "maritime-3": () => import("./real-faces/face-maritime-3.ts"),
  "fell-1": () => import("./real-faces/face-fell-1.ts"),
  "fell-2": () => import("./real-faces/face-fell-2.ts"),
  "fell-3": () => import("./real-faces/face-fell-3.ts"),
  "fell-4": () => import("./real-faces/face-fell-4.ts"),
  "fell-5": () => import("./real-faces/face-fell-5.ts"),
  "fell-6": () => import("./real-faces/face-fell-6.ts"),
  "fell-7": () => import("./real-faces/face-fell-7.ts"),
  "fell-8": () => import("./real-faces/face-fell-8.ts"),
  "fell-9": () => import("./real-faces/face-fell-9.ts"),
  "fell-10": () => import("./real-faces/face-fell-10.ts"),
  "fell-11": () => import("./real-faces/face-fell-11.ts"),
  "fell-12": () => import("./real-faces/face-fell-12.ts"),
  "fell-13": () => import("./real-faces/face-fell-13.ts"),
  "fell-14": () => import("./real-faces/face-fell-14.ts"),
  "fell-15": () => import("./real-faces/face-fell-15.ts"),
  "fell-16": () => import("./real-faces/face-fell-16.ts"),
  "fell-17": () => import("./real-faces/face-fell-17.ts"),
  "fell-18": () => import("./real-faces/face-fell-18.ts"),
  "fell-19": () => import("./real-faces/face-fell-19.ts"),
  "fell-20": () => import("./real-faces/face-fell-20.ts"),
  "fell-21": () => import("./real-faces/face-fell-21.ts"),
  "maritime-4": () => import("./real-faces/face-maritime-4.ts"),
};
