// SPDX-License-Identifier: ODbL-1.0
// GENERATED by `make real-hints ARGS=--write` (scripts/real-hints.mjs) —
// never edit by hand. Which piste grades each real face's ski area signs,
// read off OpenStreetMap, © OpenStreetMap contributors, under the Open
// Database Licence 1.0 (docs/real-faces.md), and where each face's hints
// are kept (`real-hints/hints-<id>.ts`, loaded only when a map is raised
// on it); `real-hints.ts` reads it.

import type { RunGrade } from "./grades.ts";

/** One face's hints as baked: its id and the bytes, base64. */
export type HintData = {
  readonly id: string;
  readonly data: string;
};

/** A lift's ends and a piste's bends are kept in steps of `coarse` m and
 * the piste's width at each bend in steps of `width` m (0 unknown), a
 * house's middle in steps of `fine` m and its size in steps of `size` m,
 * its bearing in `bearings` steps round half a turn. */
export const HINT_GRAIN = { coarse: 2, fine: 1, size: 1, width: 2, bearings: 32 } as const;

/** The grades of the real pistes on each face that has hints. */
export const HINT_GRADES: Readonly<Record<string, readonly RunGrade[]>> = {
  "alpine-1": ["green", "blue", "red", "black"],
  "alpine-2": ["green", "blue", "red", "black", "orange"],
  "alpine-3": ["green", "blue", "red", "black", "orange"],
  "alpine-4": ["green", "blue", "red", "black", "orange"],
  "alpine-5": ["green", "blue", "red", "black", "orange"],
  "alpine-6": ["green", "blue", "red", "black"],
  "alpine-7": ["blue", "red", "black", "orange"],
  "alpine-8": ["blue", "red", "black", "orange"],
  "alpine-9": ["blue", "red", "black", "orange"],
  "alpine-10": ["red", "black", "orange"],
  "alpine-11": ["blue", "red", "black"],
  "continental-1": ["green", "blue", "black"],
  "continental-2": ["green", "blue", "black", "orange"],
  "continental-3": ["green", "blue", "black", "orange"],
  "continental-4": ["blue", "black"],
  "maritime-1": ["green", "blue", "black", "orange"],
  "maritime-2": ["green", "blue", "black", "orange"],
  "maritime-3": ["green", "blue", "black"],
  "fell-1": ["green", "blue", "red", "black", "orange"],
  "fell-2": ["green", "blue", "red", "black"],
  "fell-3": ["green", "blue", "red", "black", "orange"],
  "fell-4": ["green", "blue", "red", "black"],
  "fell-5": ["green", "blue", "red", "black"],
  "fell-6": ["green", "blue", "red", "black"],
  "fell-7": ["green", "blue", "red", "orange"],
  "fell-8": ["green", "blue", "red", "black"],
  "fell-9": ["green", "blue", "red", "black", "orange"],
  "fell-10": ["green", "blue", "red", "black"],
  "fell-11": ["green", "blue", "red", "black"],
  "fell-12": ["green", "blue", "red", "black"],
  "fell-13": ["green", "blue", "red", "black"],
  "fell-14": ["green", "blue", "red", "black"],
  "fell-15": ["green", "blue", "red", "black"],
  "fell-16": ["green", "blue", "red", "black", "orange"],
  "fell-17": ["green", "blue", "red", "black"],
  "fell-18": ["green", "blue", "red", "black", "orange"],
  "fell-19": ["green", "blue", "red", "black", "orange"],
  "fell-20": ["green", "blue", "red", "black"],
  "fell-21": ["green", "blue", "red", "black"],
  "maritime-4": ["green", "blue", "red", "black"],
};

/** Each wooded face's woods by height, read off the forest the map draws:
 * the tree line's share of the face's relief (its lowest sample to its
 * highest), then each of `bands` bands' share wooded, bottom first, a
 * byte each (0..255), as hex. A face with none takes its region's row. */
export const HINT_TREES_BANDS = 8;

export const HINT_TREES: Readonly<Record<string, string>> = {
  "alpine-2": "65c2683a0300000000",
  "alpine-4": "70407c721000000000",
  "alpine-5": "aac0bcbd923d090000",
  "alpine-6": "2b6f09050200000000",
  "alpine-7": "7a58b5db6c00000000",
  "alpine-8": "d540be9aa0a5882500",
  "alpine-9": "6a4c94790b00000000",
  "alpine-10": "8571d2e08705000000",
  "alpine-11": "7a50e1d06500000000",
  "continental-1": "ff1c647962767d634e",
  "continental-2": "9f85cbc19345030000",
  "continental-3": "ff1ebabab1ac9c9cac",
  "continental-4": "ff23586f543d4b5459",
  "maritime-1": "ff51c3e1cbc1bdbcbe",
  "maritime-2": "ff7ec1d1dabba7b56a",
  "maritime-3": "ff6dc2dbeeddbebda1",
  "fell-1": "8f1fc2b8bb1e000000",
  "fell-2": "bf7edbc2b5ae360400",
  "fell-3": "aa71a0cd982c070000",
  "fell-4": "d5dfeae5dec6951f00",
  "fell-5": "caf2b687d5edb10d00",
  "fell-6": "ff3fc0d8e4edd5d7aa",
  "fell-7": "102d00000000000000",
  "fell-8": "aa8cc7c09b2c0b0000",
  "fell-9": "6a8ec15d0f00000000",
  "fell-10": "d5c1f6b45d668d3000",
  "fell-11": "a55d7dcbbf6a070000",
  "fell-12": "a54d6acc9b44060000",
  "fell-13": "fa7be3ede3e2f2cb6d",
  "fell-14": "506b9e190000000000",
  "fell-15": "a535d9eec35b050000",
  "fell-17": "cf8a97a6a4bd8c1400",
  "fell-18": "ff2d33789fbc6e826f",
  "fell-19": "fa2ac2b1dbdfccd034",
  "fell-20": "9fba2da0be61010000",
  "fell-21": "80b4cacd4601000000",
  "maritime-4": "9540afb18128010000",
};

/** Each face's hints, fetched when a map is raised on it. */
export const HINT_LOADERS: Readonly<Record<string, () => Promise<{ HINTS: HintData }>>> = {
  "alpine-1": () => import("./real-hints/hints-alpine-1.ts"),
  "alpine-2": () => import("./real-hints/hints-alpine-2.ts"),
  "alpine-3": () => import("./real-hints/hints-alpine-3.ts"),
  "alpine-4": () => import("./real-hints/hints-alpine-4.ts"),
  "alpine-5": () => import("./real-hints/hints-alpine-5.ts"),
  "alpine-6": () => import("./real-hints/hints-alpine-6.ts"),
  "alpine-7": () => import("./real-hints/hints-alpine-7.ts"),
  "alpine-8": () => import("./real-hints/hints-alpine-8.ts"),
  "alpine-9": () => import("./real-hints/hints-alpine-9.ts"),
  "alpine-10": () => import("./real-hints/hints-alpine-10.ts"),
  "alpine-11": () => import("./real-hints/hints-alpine-11.ts"),
  "continental-1": () => import("./real-hints/hints-continental-1.ts"),
  "continental-2": () => import("./real-hints/hints-continental-2.ts"),
  "continental-3": () => import("./real-hints/hints-continental-3.ts"),
  "continental-4": () => import("./real-hints/hints-continental-4.ts"),
  "maritime-1": () => import("./real-hints/hints-maritime-1.ts"),
  "maritime-2": () => import("./real-hints/hints-maritime-2.ts"),
  "maritime-3": () => import("./real-hints/hints-maritime-3.ts"),
  "fell-1": () => import("./real-hints/hints-fell-1.ts"),
  "fell-2": () => import("./real-hints/hints-fell-2.ts"),
  "fell-3": () => import("./real-hints/hints-fell-3.ts"),
  "fell-4": () => import("./real-hints/hints-fell-4.ts"),
  "fell-5": () => import("./real-hints/hints-fell-5.ts"),
  "fell-6": () => import("./real-hints/hints-fell-6.ts"),
  "fell-7": () => import("./real-hints/hints-fell-7.ts"),
  "fell-8": () => import("./real-hints/hints-fell-8.ts"),
  "fell-9": () => import("./real-hints/hints-fell-9.ts"),
  "fell-10": () => import("./real-hints/hints-fell-10.ts"),
  "fell-11": () => import("./real-hints/hints-fell-11.ts"),
  "fell-12": () => import("./real-hints/hints-fell-12.ts"),
  "fell-13": () => import("./real-hints/hints-fell-13.ts"),
  "fell-14": () => import("./real-hints/hints-fell-14.ts"),
  "fell-15": () => import("./real-hints/hints-fell-15.ts"),
  "fell-16": () => import("./real-hints/hints-fell-16.ts"),
  "fell-17": () => import("./real-hints/hints-fell-17.ts"),
  "fell-18": () => import("./real-hints/hints-fell-18.ts"),
  "fell-19": () => import("./real-hints/hints-fell-19.ts"),
  "fell-20": () => import("./real-hints/hints-fell-20.ts"),
  "fell-21": () => import("./real-hints/hints-fell-21.ts"),
  "maritime-4": () => import("./real-hints/hints-maritime-4.ts"),
};
