#!/usr/bin/env node
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// THE CAMPAIGN'S ROUTES — every pinned map built on its own generator version
// and its piste written down as the line its box on the card draws
// (`pwa/src/game/route-shape.ts`), into `pwa/src/game/campaign-routes.ts`:
// the campaign's maps, and the trick maps (`trick-maps.ts`) after them.
// Pure Node, a second a map.
//
//   make routes            rewrite the table
//   make routes ARGS=--check   exit non-zero where the table and the maps disagree
//
// The table is GENERATED and never hand-edited; `tests/generator_version_test.ts`
// rebuilds every pinned map and holds its line to the one written here, so a
// map added to `campaign-levels.ts` without a `make routes` is a red suite.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";

import { parseArgs } from "@niclaslindstedt/oss-game-framework/tooling/cli";
import { aliasEngine } from "@niclaslindstedt/oss-game-framework/tooling/alias";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
aliasEngine(root);
const { CAMPAIGN_LEVELS, buildCampaignLevel } = await import(
  join(root, "pwa/src/game/campaign.ts")
);
const { TRICK_MAPS, buildTrickMap } = await import(join(root, "pwa/src/game/trick-maps.ts"));
const { routeOf } = await import(join(root, "pwa/src/game/route-shape.ts"));

const args = parseArgs(
  process.argv.slice(2),
  { check: { kind: "flag", help: "compare instead of writing; exit 1 on a difference" } },
  "usage: npm run routes -- [--check]",
);

const file = join(root, "pwa/src/game/campaign-routes.ts");
const pinnedMaps = [
  ...CAMPAIGN_LEVELS.map((pinned) => ({ pinned, build: () => buildCampaignLevel(pinned) })),
  ...TRICK_MAPS.map((pinned) => ({ pinned, build: () => buildTrickMap(pinned) })),
];
const rows = pinnedMaps.map(({ pinned, build }) => {
  const level = build();
  console.log(
    `${pinned.id.padEnd(14)} seed ${String(pinned.seed).padStart(4)}  v${pinned.version}`,
  );
  return `  "${pinned.id}":\n    "${routeOf(level)}",`;
});
const text = `// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// GENERATED by \`make routes\` (scripts/campaign-routes.mjs) — do not edit.
// Every campaign map's piste, and every trick map's, as the line its box draws
// (\`route-shape.ts\`); \`tests/generator_version_test.ts\` and
// \`tests/trick_maps_test.ts\` hold each line to the map it pictures.

/** The line behind each campaign box and trick map box, by map id. */
export const CAMPAIGN_ROUTES: Readonly<Record<string, string>> = {
${rows.join("\n")}
};
`;

if (args.check) {
  let stood = "";
  try {
    stood = readFileSync(file, "utf8");
  } catch {
    /* no table yet */
  }
  if (stood !== text) {
    console.error(`${file} is stale — run \`make routes\``);
    process.exit(1);
  }
  console.log("the routes table matches every pinned map");
} else {
  writeFileSync(file, text);
  console.log(`wrote ${file}`);
}
